### ISSUE TITLE
Paused Music continues to play when video is paused

### ISSUE THREAD

**Issue by Giluxis** [ericleroy01/synoMediaStation#1]
Thanks for making this project. Since Synology isn't supporting a Media app for XBOX One this is very useful.

The issue I have noticed : Play music and pause. Then play a video and pause. Music begins to play again until video is resumed.

**Comment by ericleroy01** [comment]
I don't reproduce this issue on windows (not yet tested on XBOX)

**Comment by ericleroy01** [comment]
fixed

**Comment by Giluxis** [comment]
Thanks
