### ISSUE TITLE
Feature request: HTTPS ignore insecure certificate

### ISSUE THREAD

**Issue by aioue** [ericleroy01/synoMediaStation#13]
Am using the default Synology certificate, please allow HTTPS to ignore a self-signed cert.

**Comment by ericleroy01** [comment]
to my mind, it s not recommended to authorize connection to unsecure server via https.

why don't you use let's encrypt certificates ?

synology provide a way to get a certificate : [How do I obtain a certificate from Let's Encrypt on my Synology NAS?](https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Network/How_to_enable_HTTPS_and_create_a_certificate_signing_request_on_your_Synology_NAS)
