### ISSUE TITLE
App closes when a video finishes playing

### ISSUE THREAD

**Issue by Tofandel** [ericleroy01/synoMediaStation#15]
This app is really a life saver from the DS video interface which doesn't play 60% of codecs but there is a few issues staining the user experience:

After a video ends, the app just closes itself on windows 11, this is very annoying when watching short series (AKA 20 minute episodes), combined with the fact that there is a 20 seconds timer before being able to log in (for no reason, because the ad displayed there is just a banner)

**Comment by ericleroy01** [comment]
Hi, I will re-write this app soon
some issues with Xbox & 4k video
