### ISSUE TITLE
Connect to a Synology nas

### ISSUE THREAD

**Issue by Tealy44** [ericleroy01/synoMediaStation#17]
As you able to give an example of what you would put in the connection settings to connect to a Synology nas on you network as I can't figure out what to put in to connect. The os is the latest dsm 7.2.1

**Comment by ericleroy01** [comment]
Hi, here is a sample
Server: 192.168.1.100:5000
5000 is default port
5001 is default https port

Check https checkbox if needed

**Comment by Tealy44** [comment]
Great that worked thanks
