### ISSUE TITLE
SynoMediaStation Crashes on playback

### ISSUE THREAD

**Issue by Giluxis** [ericleroy01/synoMediaStation#2]
When starting certain files that will open and play fine in VLC; SMS freezes and crashes to XBOXone Main and must be reloaded. Will not play same file. I can supply details on request.

**Comment by ericleroy01** [comment]
Could you send me a video sample ?

**Comment by Giluxis** [comment]
I process all video by removing commercials in Avidemux which saves as a 
MKV by default then compressed as a M4V in Handbrake. All M4V versions 
of this entire season of shows freeze and crash SMS in the same place at 
the very beginning. But play fine in the VLC for XBOX One app.

The MKV version of this clip that I am sending does not freeze or crash. 
Both are cut from the same video

https://drive.google.com/drive/folders/127AVUeITa9O3_aptcKc-aNoV60rF3-Xl?usp=sharing


Jim

**Comment by ericleroy01** [comment]
I need to reproduce the issue with your file :(

**Comment by ericleroy01** [comment]
for your information SMS is based on VLC components

**Comment by ericleroy01** [comment]
is there a link with https://github.com/ericleroy01/synoMediaStation/issues/5 issue ?

**Comment by Giluxis** [comment]
This crash issue seems to be resolved and was limited to a limited number of files, I could not reproduce it in VLC.

 The #5 issue seems to be different and related to the H.265 encoding. 
 
 re: #5 I have noticed that when a video is encoded in H.264 and paused then resumed. The video will hang slightly at about the same point where it freezes with H.265. If that helps.

**Comment by ericleroy01** [comment]
fixed with release 1.10.14.0
