### ISSUE TITLE
2FA Account Support

### ISSUE THREAD

**Issue by ghost** [ericleroy01/synoMediaStation#4]
Access to my NAS is protected via 2FA.
synoMediaStation does not recognise, nor allow login to protected accounts.

**Comment by ericleroy01** [comment]
Can you connect to your nas by using DSVideo or DSAudio ?

 

 

Cordialement,

Eric LE ROY

 

*  <tel:+33671379546> +33 6 71 37 95 46

*  <mailto:eric.le.roy@free.fr> eric.le.roy@free.fr

 

De : Daniel Fox <notifications@github.com> 
Envoyé : mardi 22 septembre 2020 10:14
À : ericleroy01/synoMediaStation <synoMediaStation@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [ericleroy01/synoMediaStation] 2FA Account Support (#4)

 

Access to my NAS is protected via 2FA.
synoMediaStation does not recognise, nor allow login to protected accounts.

**Comment by ericleroy01** [comment]
fixed and available with release 1.0.9
