### ISSUE TITLE
Video freezes after pause and resume video

### ISSUE THREAD

**Issue by Giluxis** [ericleroy01/synoMediaStation#5]
Thanks for improving this app!

I have noticed with the previous and most current version that when a video is paused and resumed the video will freeze when continues but the audio will resume. The only way to continue properly is to bag out off the video and restart from the current location. Most videos on my system are encoded as MKV or M4V. I have not tried with an MPG.

XBOX One S, Synology DS418play DSM 6.2.3-25426

**Comment by ericleroy01** [comment]
Hi, I will check this issue asap.

**Comment by ericleroy01** [comment]
I can t reproduce
can you send me encoding parameters (video & audio)?

**Comment by Giluxis** [comment]
This is an example of the encoding of my files. All freeze in the same way. I pause the video at a random place and resume. The video is frozen and the audio continues . I can only resolve the issue by exiting the video and resuming.

[example encoding.txt](https://github.com/ericleroy01/synoMediaStation/files/5820669/example.encoding.txt)

**Comment by ericleroy01** [comment]
you use x265 codec....do you reproduce this issue with x264 one ?

video player is based on VLC components. Do you reproduce this issue with VLC App ?

**Comment by Giluxis** [comment]
You are correct. The problem is with the way VLC handles x265. My mistake, sorry.

**Comment by ericleroy01** [comment]
no problem.
may be you should post an issue on VLC website

**Comment by ericleroy01** [comment]
a new release is available on Microsoft Store.
I don't reproduce x265 codec issue anymore.

issue will be closed if you confirm

**Comment by Giluxis** [comment]
I had to download and reinstall to get the new release. I confirm that the video freeze is solved.

But now the transport function buttons on my remote don't work. Play/Pause < > << >> etc.

I can use the built in features in the app to do these things but it is inconvenient. 

Sorry.

**Comment by Razieldroid** [comment]
Hi, 
On Xbox OneX, with the Xbox media controller (the old small one), The play/pause & fast forward-rewind buttons work fine On my side. 
The pause problem during x265 video is fixed for me.
Best regards.

**Comment by Giluxis** [comment]
I'm probably mistaken. I use a Talon Media Remote for the Xbox One and have checked this with VLC and it doesn't work there either.  Sorry. These buttons do work on other video apps that I have on the box. Showtime, Amazon Prime. HDHomerun DVR etc.

Thank you for keeping up with this. It functions very well. You should offer a lifetime purchase option.

**Comment by ericleroy01** [comment]
x265 issue is solved.

Crreate a issue relative to remote controller

**Comment by ericleroy01** [comment]
fixed with release 1.10.14.0
